export const Constants={
    saveText:"Click on this to Save this manifest as a draft",
    scheduleText:"Click on this to Schedule your selections to publish",
    clearText:"Click on this to clear all the selectors",
    joinText:"Click on this to add join between Tables",
    filterText:"Click on this to add Filters between Tables & Columns",
    editText:"Click on this to edit datatype",
    saveData:"Click on this to save datatype",
    deleteText:"Click on this to delete column",
    showFilter:"Click on this to edit Filter data",
    deleteFilter:"Click on this to delete Filter data",
    clickJoin:"Click on this to clear selected Table/Column",
    addJoin:"Click on this to Join selecetd Column",
    editJoin:"Click on this to edit Join ",
    deleteJoin:"Click on this to delete Join ",
    updateJoin:"Click on this to update Join ",
    clearFilter:"Click on this to clear data",
    addFilter:"Click on this to add another Filter",
    editSchedule:"Click on this to edit schedule",
    clearSchedule:"Click on this to clear schedule selection",
    scheduleData:"Click on this to Publish selected Manifest",
    cronSchedule:"1. Cron is most suitable for scheduling repetitive tasks to run periodically at fixed times,dtes,or intervals 2.asterisk ( * )  Specifies all possible values for a field   An asterisk in the hour time field is equivalent to “every hour” 3.A question mark ( ? ) is allowed in the day-of-month and day-of-week fields  4.The pound sign ( # ) character is allowed for the day-of-week field. This character is used to specify “the nth” xxx day of the month 5.slash ( / ) Used to skip a given number of values   Example:0 15 10 ? * *	Fire at 10:15 AM every day",
    cronExp1:"2.asterisk ( * )  Specifies all possible values for a field   An asterisk in the hour time field is equivalent to “every hour”",
    cronExp2:"3.A question mark ( ? ) is allowed in the day-of-month and day-of-week fields",
    cronExp3:"4.The pound sign ( # ) character is allowed for the day-of-week field. This character is used to specify “the nth” xxx day of the month",
    cronExp4:"5.slash ( / ) Used to skip a given number of values",
    editPublish:"Click on this to edit schedule",
    deletePublish:"Click on this to delete schedule",
    validate:"Click on this to Validate the given CRON expression",
}